### ISSUE TITLE
Tao cau truc thu muc cho tai lieu

### ISSUE THREAD

**Issue by congto** [meditechopen/meditech-ghichep-rabbitmq#3]
@hoangdh Em tạo cấu trúc thư mục tài liệu như sau
`docs` : chứa các tài liệu, trong đó có các thư mục con
`images` : chứa các hình ảnh để chèn vào bài viết
`tools`: chứa các công cụ, chương trình mình viết (trích dẫn tới trong các tài liệu)

Em tạo lại xong moving các tài liệu cũ vào nhé.

**Comment by hoangdh** [comment]
Ok. em đã chỉnh cấu trúc lại repo và sửa xong một số lỗi chính tả trong bài tìm hiểu.
